### ISSUE TITLE
twitter 4j for ads-api 

### ISSUE THREAD

**Issue by manopriyan** [sprinklr-inc/twitter4j-ads#1]
already i am using twitter4j library now i need to get datas from ads api any additional jar file need to download for access ads api in twitter4j

**Comment by jbabichjapan** [comment]
The JAR has not yet been pushed to Maven but it will be very soon. Please see the instructions in README.md and you should be able to build and reference it with the included Gradle file.

**Comment by abhishekanand100** [comment]
Pom:
<dependency>
    <groupId>com.sprinklr</groupId>
    <artifactId>twitter4j-ads</artifactId>
    <version>1.0</version>
</dependency>

Gradle:
compile 'com.sprinklr:twitter4j-ads:1.0'

For others please refer to http://search.maven.org/#artifactdetails%7Ccom.sprinklr%7Ctwitter4j-ads%7C1.0%7Cjar
