### ISSUE TITLE
cardsApi - can't find method to create cards?

### ISSUE THREAD

**Issue by seraphimalia** [sprinklr-inc/twitter4j-ads#18]
Hi Guys,

I don't see any way to create Cards using the cards API.

Please assist?

Seraph

**Comment by pradubey** [comment]
There isn't any method to create cards in the current version. We hope to add it soon.

**Comment by seraphimalia** [comment]
Thanks, may I add it and submit a PR?

Clive Munro
Twitter Communications

Cell:   082 654 9079<tel://+27.826549079>
Email:   clivem@communitymedics.org.za<mailto:clivem@communitymedics.org.za>
Website:   www.communitymedics.org.za<http://communitymedics.org.za/>
PBO Reg No. :   930 029 619<tel:930%20029%20619>

[Community Medics Logo]


On 02 Sep 2016, 8:25 PM +0200, Prashant Dubey <notifications@github.com>, wrote:

There isn't any method to create cards in the current version. We hope to add it soon.

**Comment by pradubey** [comment]
Yeah, you are welcome.

**Comment by abhishekanand100** [comment]
This is available in v2.1
