### ISSUE TITLE
twitter4j.models.ads.AdAccount.getCurrency() returning null

### ISSUE THREAD

**Issue by lpereirafernandez** [sprinklr-inc/twitter4j-ads#26]
So far I could just test this with my own Ads account, but when pulling the available accounts with the method TwitterAdsAccountApi.getAllAccounts(), and then the call to adAccount.getCurrency() is returning null.

Many thanks in advance,
Luis

**Comment by abhishekanand100** [comment]
@lpereirafernandez please use the currency from the funding instrument rather than the ad account

https://dev.twitter.com/ads/reference/get/accounts
