### ISSUE TITLE
TwitterAdsPromotedTweetApi.getAllPromotedTweets() takes deprecated parameter lineItemId

### ISSUE THREAD

**Issue by lpereirafernandez** [sprinklr-inc/twitter4j-ads#30]
Hi there,

We noticed the method TwitterAdsPromotedTweetApi.getAllPromotedTweets() only takes the deprecated parameter lineItemId and doesn't offer the ability to pass a list of line item ids as the endpoint https://dev.twitter.com/ads/reference/get/accounts/%3Aaccount_id/promoted_tweets

Many thanks in advance,
Luis

**Comment by jbabichjapan** [comment]
Thanks for the heads up about this...This was fixed in the last commit! More changes will come in the next couple days.
