### ISSUE TITLE
Maven Repository Status

### ISSUE THREAD

**Issue by zmcarlson** [sprinklr-inc/twitter4j-ads#33]
I'd like to utilize the maven repository but I'm not sure if 1.0 is the latest version since it hasn't been updated since May 2016. Is this the latest stable release?

https://mvnrepository.com/artifact/com.sprinklr/twitter4j-ads/ #

**Comment by camillagm** [comment]
I'm looking for the last version too. I even tried to build it from the source code but it showed a few errors (some missing classes). Gradle couldn't finish the build.

**Comment by abhishekanand100** [comment]
This will be pushed by the 26th Feb latest.

**Comment by zmcarlson** [comment]
Ok, any status on this?

**Comment by abhishekanand100** [comment]
Please check on Monday, the updation would reflect for new version.

*abhishek **anand*
developer l sprinklr <http://www.sprinklr.com/>


*enabling businesses to build real, human relationships.9th Floor, IRIS
Tech Park, Sector 48, Sohna Road, Gurgaonm: (+91)8447023343 skype:
abhishekanand100"the most powerful technology in the market"
<http://www.sprinklr.com/social-scale-blog/2013/04/17/sprinklr-judged-best-social-relationship-platform-forresters-wave/>
- forrester research*

**Comment by zmcarlson** [comment]
Checking in on this again, it appears the newest version wasn't pushed.

https://mvnrepository.com/artifact/com.sprinklr/twitter4j-ads

**Comment by abhayb1988** [comment]
The latest release 1.1 is finally out. Please share your feedback on the same.
