### ISSUE TITLE
v2 of the Twitter Ads API

### ISSUE THREAD

**Issue by dpogorelov** [sprinklr-inc/twitter4j-ads#40]
I'm very sorry that I created the issue but maybe it will be also actual for another developers who want to ask about supported Twitter ADS API version by the twitter4j-ads library. As I know the v1 will be turned off on January 10th, 2018 by Twitter. Could you tell me please if the current twitter4j-ads library (1.1 version) supports Twitter ADS API v2? Or a new special twitter4j-ads library version will be released to support the Twitter ADS API v2?
Thank you.

**Comment by jbabichjapan** [comment]
The target to release v2 compatible version is this week - the process of uploading JAR to Maven is still manual and time consuming but definitely want to say that community help is appreciated to test the changes, add anything missed, add test coverage etc. Until there is CI to test and automatically release setup we can only update the Maven JAR on something like a quarterly schedule.

**Comment by abhishekanand100** [comment]
v 2.1 has been released
