### ISSUE TITLE
Build failure due to class name/file name mismatch

### ISSUE THREAD

**Issue by frankgrimes97** [sprinklr-inc/twitter4j-ads#42]
TwitterVideoDmCard.java should be renamed to TwitterVideoDMCard.java

```
twitter4j-ads/twitter4j-ads/src/twitter4j/models/ads/cards/TwitterVideoDmCard.java:10: error: class TwitterVideoDMCard is public, should be declared in a file named TwitterVideoDMCard.java
public class TwitterVideoDMCard extends AbstractTwitterDMCard {
       ^
```

**Comment by abhishekanand100** [comment]
Apologies for this

File names under OS X are not case sensitive (by default). This is more of an OS problem than a git problem. If you remove and re-add the file you should get what you want, or rename it to something else and then rename it back.

Pushing a fresher maven version with compilable code

**Comment by abhishekanand100** [comment]
<dependency>
  <groupId>com.sprinklr</groupId>
  <artifactId>twitter4j-ads</artifactId>
  <version>2.1</version>
</dependency>
