### ISSUE TITLE
v2 changes in TwitterAdsPromotedTweetApi remove possibility of filtering by lineItemId

### ISSUE THREAD

**Issue by frankgrimes97** [sprinklr-inc/twitter4j-ads#43]
This change removes necessary filtering by lineItemId:

https://github.com/sprinklr-inc/twitter4j-ads/commit/7ec7b432202ad74c1e79fdeef23fee00788541c8#diff-b919ebda3da5967e5d4cea251abc3438

In v2 of the Twitter Ads API, a list of lineItemIds can be passed instead.

**Comment by abhishekanand100** [comment]
We have removed the line_item_id parameter from the GET accounts/:account_id/promoted_tweets endpoint, which we previously marked as deprecated. (Note: the line_item_ids parameter is not affected.)

https://twittercommunity.com/t/ads-api-version-2/90360?utm_campaign=OT_NW_ADS_Updates_US_EN_171027&utm_medium=email&utm_source=Eloqua

**Comment by frankgrimes97** [comment]
My point was that the line_item_ids parameter doesn't seem to be exposed at all: https://github.com/sprinklr-inc/twitter4j-ads/blob/master/twitter4j-ads/src/twitter4j/api/TwitterAdsPromotedTweetApi.java#L32

Am I missing something?
