### ISSUE TITLE
The line_item_ids parameter is missing from TwitterAdsPromotedTweetApi.getAllPromotedTweets()

### ISSUE THREAD

**Issue by frankgrimes97** [sprinklr-inc/twitter4j-ads#44]
Previously a line_item_id parameter was exposed but since it was remove in v2 it needs to be replaced with line_item_ids.

**Comment by felipeAndrade0918** [comment]
Yep, I am having the same problem here.

**Comment by frankgrimes97** [comment]
Seems to be fixed now: https://github.com/sprinklr-inc/twitter4j-ads/commit/b1986ecf680657d51554bd47bae9acb487192b9e#diff-9b67c2c50d58f3b3881d455bf7ecba01
