### ISSUE TITLE
Missing params in Preview

### ISSUE THREAD

**Issue by abhayb1988** [sprinklr-inc/twitter4j-ads#7]
getPromotedTweetPreview is missing preview Target parameter

**Comment by abhishekanand100** [comment]
Hello Abhay

Yes this is present in the method

BaseAdsListResponse<TwitterPreviewInfo> getPromotedTweetPreview(String accountId, String tweetId, String userId, TwitterPreviewTarget twitterPreviewTarget) throws TwitterException;

Cheers
